name: at_client
description: The at_client library is the non-platform specific Client SDK which provides the essential methods for building an app using the @protocol.
version: 3.0.18
repository: https://github.com/atsign-foundation/at_client_sdk
homepage: https://atsign.dev
documentation: https://atsign.dev/docs/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  hive: ^2.0.4
  crypton: ^2.0.1
  encrypt: ^5.0.0
  cron: ^0.3.0
  convert: ^3.0.0
  uuid: ^3.0.4
  crypto: ^3.0.1
  collection: ^1.15.0
  lints: ^1.0.1
  archive: ^3.1.2
  http: ^0.13.3
  internet_connection_checker: ^0.0.1+2
  async: ^2.8.2
  at_persistence_spec: ^2.0.5
  at_persistence_secondary_server: ^3.0.23
  at_lookup: ^3.0.18
  at_utf7: ^1.0.0
  at_base2e15: ^1.0.0
  at_commons: ^3.0.12
  at_utils: ^3.0.9

#dependency_overrides:
#  at_persistence_spec:
#    git:
#      url: https://github.com/atsign-foundation/at_server.git
#      path: at_persistence/at_persistence_spec
#      ref: trunk
#  at_utils:
#    git:
#      url: https://github.com/atsign-foundation/at_tools.git
#      path: at_utils
#      ref: trunk
#  at_commons:
#    git:
#      url: https://github.com/atsign-foundation/at_tools.git
#      path: at_commons
#      ref: trunk
#  at_persistence_secondary_server:
#    git:
#      url: https://github.com/atsign-foundation/at_server.git
#      path: at_secondary/at_persistence_secondary_server
#      ref: trunk
#  at_lookup:
#    git:
#      url: https://github.com/atsign-foundation/at_libraries.git
#      path: at_lookup
#      ref: trunk

dev_dependencies:
  test: ^1.17.2
  at_demo_data: ^0.0.3+1
  coverage: ^1.0.3
  mocktail: ^0.3.0
  dart_code_metrics: ^4.8.1
