name: at_client
description: The at_client library is the non-platform specific Client SDK which provides the essential methods for building an app using the atProtocol.
## When incrementing the version, update the version in AtClientConfig file
version: 3.0.41
repository: https://github.com/atsign-foundation/at_client_sdk
homepage: https://atsign.dev
documentation: https://docs.atsign.com/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.2
  hive: ^2.0.4
  crypton: ^2.0.5
  encrypt: ^5.0.1
  cron: ^0.5.0
  convert: ^3.0.2
  uuid: ^3.0.6
  crypto: ^3.0.1
  collection: ^1.16.0
  archive: ^3.3.1
  http: ^0.13.5
  internet_connection_checker: ^0.0.1+4
  async: ^2.9.0
  at_persistence_spec: ^2.0.7
  at_persistence_secondary_server: ^3.0.39
  at_lookup: ^3.0.30
  at_utf7: ^1.0.0
  at_base2e15: ^1.0.0
  at_commons: ^3.0.27
  at_utils: ^3.0.11
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
  at_demo_data: ^1.0.0
  coverage: ^1.5.0
  mocktail: ^0.3.0
  dart_code_metrics: ^4.17.0
