name: at_client
description: at_client is the Client SDK which provides the essential methods for building an app using the @protocol.
version: 1.0.1+7
repository: https://github.com/atsign-foundation/at_client_sdk
homepage: https://atsign.dev
documentation: https://atsign.dev/at_docs-dev_env/at_client/index.html

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: ^1.6.0
  utf7: ^0.2.1
  hive: ^1.3.0
  crypton: ^1.1.0
  encrypt: ^4.0.2
  cron: ^0.2.2
  convert: ^2.1.1
  base2e15: ^0.3.0
  uuid: ^2.0.2
  crypto: ^2.1.5
  collection: ^1.14.12
  pedantic: ^1.8.0
  at_persistence_spec: ^1.0.1+3
  at_persistence_secondary_server: ^1.0.1+5
  at_lookup: ^1.0.0+5
  at_commons: ^1.0.1+5
  at_utils: ^1.0.1+5

dev_dependencies:
  test: ^1.6.0
