name: at_end2end_test
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://www.atsign.com

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  at_client:
    path: ../at_client

#   at_commons:
#     git:
#       url: https://github.com/atsign-foundation/at_tools.git
#       path: at_commons
#       ref: trunk

#  at_lookup:
#    git:
#      url: https://github.com/atsign-foundation/at_libraries.git
#      path: at_lookup
#      ref: deprecate_find_secondary

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
