name: at_client_mobile_example
description: Library for mobile app onboarding.
version: 1.0.0
repository: https://github.com/atsign-foundation/at_client_sdk
homepage: https://atsign.dev
documentation: https://atsign.dev/at_docs-dev_env/at_client_mobile/at_client_mobile/at_client_mobile-library.html

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: ^1.6.0
  flutter:
    sdk: flutter
  flutter_keychain: ^1.0.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
