name: at_functional_test
publish_to: none
description: Functional tests for the at_client_sdk packages
version: 1.0.0

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  at_client:
    path: ../at_client

dependency_overrides:
  at_commons:
    git:
      url: https://github.com/atsign-foundation/at_tools.git
      path: at_commons
      ref: encode_public_data
  at_persistence_spec:
    git:
      url: https://github.com/atsign-foundation/at_server.git
      path: at_persistence/at_persistence_spec
      ref: encode_public_data
  at_persistence_secondary_server:
    git:
      url: https://github.com/atsign-foundation/at_server.git
      path: at_secondary/at_persistence_secondary_server
      ref: encode_public_data

dev_dependencies:
  test: ^1.17.2
  lints: ^1.0.1
  at_demo_data: ^0.0.3+1
  coverage: ^1.0.3
