name: at_functional_test
publish_to: none
description: Functional tests for the at_client_sdk packages
version: 1.0.0

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  at_client:
    path: ../at_client

dependency_overrides:
  at_commons:
    git:
      url: https://github.com/atsign-foundation/at_tools.git
      path: at_commons
      ref: trunk
#  at_lookup:
#    git:
#      url: https://github.com/atsign-foundation/at_libraries.git
#      path: at_lookup
#      ref: deprecate_find_secondary

dev_dependencies:
  test: ^1.17.2
  lints: ^1.0.1
  at_demo_data: ^0.0.3+1
  coverage: ^1.0.3
