name: at_functional_test
publish_to: none
description: Functional tests for the at_client_sdk packages
version: 1.0.0

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  at_client:
    path: ../at_client

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.0
