name: at_client_mobile
description: A Flutter extension to the at_client library which adds support for mobile, desktop and IoT devices.
version: 3.1.19
repository: https://github.com/atsign-foundation/at_client_sdk
homepage: https://atsign.dev
documentation: https://atsign.dev/docs/functional_architecture/libraries/#at_client_mobile

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  flutter:
    sdk: flutter
  flutter_keychain: ^2.1.0
  biometric_storage: ^3.0.1
  hive: ^2.0.4
  crypton: ^2.0.3
  at_client: ^3.0.30
  at_lookup: ^3.0.27
  at_commons: ^3.0.19
  at_utils: ^3.0.10

# dependency_overrides:
#   at_client:
#     path: ../at_client
#    git:
#      url: https://github.com/atsign-foundation/at_client_sdk.git
#      path: at_lookup
#      ref: trunk
#  at_lookup:
#    git:
#      url: https://github.com/atsign-foundation/at_libraries.git
#      path: at_lookup
#      ref: trunk
#  at_utils:
#    git:
#      url: https://github.com/atsign-foundation/at_tools.git
#      path: at_utils
#      ref: trunk
#  at_commons:
#    git:
#      url: https://github.com/atsign-foundation/at_tools.git
#      path: at_commons
#      ref: trunk

dev_dependencies:
  lints: ^1.0.1
  test: ^1.6.0
