name: Auto Assign Issues to Triage column in Sprint Planning Project Board

on:
  issues:
    types: [opened]

jobs:
  issue_opened:
    name: issue_opened
    runs-on: ubuntu-latest
    steps:
      - name: 'Move issue to "Triage"'
        uses: leonsteinhaeuser/project-beta-automations@v2.0.0
        with:
          gh_token: ${{ secrets.MY_GITHUB_TOKEN }}
          organization: atsign-foundation
          project_id: 8
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: "Triage"
